### ISSUE TITLE
update the repository to reflect the current state

### ISSUE THREAD

**Issue by dirk-thomas** [ros/console_bridge#20]
The state of this repository has diverged significantly from what is actually being used / has been released latest. Currently it is not clear where future patches should be applied and how they could be released:

* ROS Indigo uses the package available from Ubuntu repositories: 0.2.5-2 (http://packages.ubuntu.com/trusty/libconsole-bridge-dev)

* ROS Hydro uses a version number far behind (0.2.4-1 http://www.ros.org/debbuild/hydro.html?q=console_bridge) since any newer release broke building packages which depend on `console_bridge`

To match user expectation I think the repo needs some clean up:

* remove the *indigo-devel* branch since that is not the `console_bridge` version being used by ROS Indigo

* update *master* to reflect what could be the next version being released:
  * it should contain the content which future versions of console bridge could be tagged from
  * if the *master* is *not* compatible with the Ubuntu package (breaking API / ABI) I think it should be made clear by bumping the version number accordingly
  * if the *master* is *not* compatible with ROS Hydro anymore I think a *hydro-devel* branch should be created from the version being used in Hydro (plus optionally any non-breaking patches which should go into a potential patch release into Hydro)

(The general rules apply that no version number should ever be reused or be available from different branches containing different code.)

**Comment by scpeters** [comment]
So if we delete the `indigo-devel` branch, can we close this issue?

**Comment by dirk-thomas** [comment]
Since Hydro has been EOLed since the ticket was created we could not care about those. But wouldn't it be easy to create a `hydro-devel` branch to make it easy if people do want to build it?

**Comment by scpeters** [comment]
Ok, so we could:

* rebase `indigo-devel` onto the 0.2.5 tag
* create `hydro-devel` from 0.2.4 tag

Is that it?

**Comment by dirk-thomas** [comment]
Yes, that should be good as far as I can tell.

**Comment by scpeters** [comment]
Ok, I created `hydro-devel` and rebased `indigo-devel` accordingly.

* https://github.com/ros/console_bridge/branches
