### ISSUE TITLE
API breakage in new version (0.3)

### ISSUE THREAD

**Issue by jspricke** [ros/console_bridge#30]
Hi,

the new version breaks the API:
```
/<<PKGBUILDDIR>>/tools/rosbag_storage/src/bz2_stream.cpp: In member function 'virtual void rosbag::BZ2Stream::read(void*, size_t)':
/<<PKGBUILDDIR>>/tools/rosbag_storage/src/bz2_stream.cpp:119:9: error: 'else' without a previous 'if'
         else {
         ^
/<<PKGBUILDDIR>>/tools/rosbag_storage/src/lz4_stream.cpp: In member function 'virtual void rosbag::LZ4Stream::read(void*, size_t)':
/<<PKGBUILDDIR>>/tools/rosbag_storage/src/lz4_stream.cpp:159:9: error: 'else' without a previous 'if'
         else {
         ^
tools/rosbag_storage/CMakeFiles/rosbag_storage.dir/build.make:137: recipe for target 'tools/rosbag_storage/CMakeFiles/rosbag_storage.dir/src/bz2_stream.cpp.o' failed
make[3]: *** [tools/rosbag_storage/CMakeFiles/rosbag_storage.dir/src/bz2_stream.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```
The problematic commit is https://github.com/ros/console_bridge/commit/4c529c62e606e3e6fdb9bca2468ad397f2c011ae.

The problem is that the `console_bridge_deprecated();` makes the macro two commands and so the binding between the `if` and the `else` is lost (see https://github.com/ros/ros_comm/blob/indigo-devel/tools/rosbag_storage/src/bz2_stream.cpp#L118).

**Comment by scpeters** [comment]
Thanks for catching this. What if we added extra `{}` scoping around the two commands?

**Comment by scpeters** [comment]
No, that won't work because the macro wants to be terminated with a `;`

**Comment by j-rivero** [comment]
Umm interesting. I have an idea, let me code it.

**Comment by scpeters** [comment]
fixed by #31

**Comment by jspricke** [comment]
Thanks! Can we get a new upstream release and Debian package? This is holding up quite some package in Debian at the moment.

**Comment by scpeters** [comment]
I just made a 0.3.1 release:

* https://github.com/ros/console_bridge/releases/tag/0.3.1

**Comment by j-rivero** [comment]
I just uploaded the 0.3.1-1 debian package into Sid.
