### ISSUE TITLE
compiler warning on Windows

### ISSUE THREAD

**Issue by dirk-thomas** [ros/console_bridge#32]
https://github.com/ros/console_bridge/blob/bbcc9141bacde590483c758f299d967ac31b7aa0/src/console.cpp#L153

> 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

http://ci.ros2.org/view/packaging/job/packaging_windows/103/warnings34Result/package.-318397937/

**Comment by scpeters** [comment]
What do you think of https://github.com/scpeters/console_bridge/commit/5c2d920d0ddf5ae962dc3b5410e7d206b170d6f

**Comment by dirk-thomas** [comment]
The compiler wants something different :wink: http://ci.ros2.org/view/packaging/job/packaging_windows/108/console

**Comment by scpeters** [comment]
At least it was only two errors (I think). Hopefully https://github.com/scpeters/console_bridge/commit/0e4574d599fc918bbb8061acf476799813e9dd87 is better

**Comment by dirk-thomas** [comment]
Thank you, looks good: http://ci.ros2.org/job/packaging_windows/109/warnings34Result/fixed/

**Comment by scpeters** [comment]
Ok, I squashed and submitted as #33
