### ISSUE TITLE
Tests failing on windows

### ISSUE THREAD

**Issue by scpeters** [ros/console_bridge#37]
I had to disable the appveyor tests in 0d83ff0d11b73b8594bae9adfa634580d0a77fc8 since the test is failing via timeout. When I run it locally, it gives a pop-up saying that the console_bridge dll could not be found. I've tried to fix it https://github.com/scpeters/console_bridge/commit/064642a250c6160ec00e06ae764cf70b280723dd, but it's not quite working yet.

**Comment by traversaro** [comment]
PR https://github.com/ros/console_bridge/pull/38

**Comment by scpeters** [comment]
closed by #38
