### ISSUE TITLE
compiler warnings with Visual Studio 2017 due to gtest

### ISSUE THREAD

**Issue by dirk-thomas** [ros/console_bridge#51]
E.g.:

```
console_bridge\test\gtest\include\gtest/gtest-printers.h(500):
warning C4996: 'std::tr1': warning STL4002:
The non-Standard std::tr1 namespace and TR1-only machinery are deprecated and will be REMOVED. You can define _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING to acknowledge that you have received this warning.
```

The warnings have been fixed upstream so pulling a newer version of the `googletest` code will likely solve this.

**Comment by dirk-thomas** [comment]
The warnings have been fixed upstream so pulling a newer version of the `googletest` code would solve this.

**Comment by scpeters** [comment]
@dirk-thomas what compiler flags do you use on windows for warnings? I'm testing a fix on my windows VM, but I don't see any warnings on the master branch, so I probably need to enable them.

**Comment by dirk-thomas** [comment]
We only build the package with the defaults (`cmake`, `make`, `make install`) afaik. The referenced build (http://ci.ros2.org/job/test_ci_win/19/) might contain the information you are looking for.

**Comment by dirk-thomas** [comment]
We can also retrigger the job with a potential fix on a branch to check if it addresses the warnings.

**Comment by scpeters** [comment]
I've added VS 2017 to our appveyor build in #53 and it is marked to fail on any compiler warnings. We'll see if appveyor can reproduce the warning because I've been having trouble doing it on my virtual machine

**Comment by scpeters** [comment]
appveyor confirms the failure in #53 

I'm updating my VS 2017 software on my VM, since it is apparently out of date

**Comment by scpeters** [comment]
I believe #54 will fix this
