### ISSUE TITLE
Compiler warnings on OSX due to the use of ## __VA_ARGS__

### ISSUE THREAD

**Issue by mikaelarguedas** [ros/console_bridge#55]
Apparently CLang complains about the use of `## __VA_ARGS__` as it is a GNU extension causing warnings on our CI:
Warning type:  `-Wgnu-zero-variadic-macro-arguments`
Warning message: "token pasting of ',' and `__VA_ARGS__` is a GNU extension"

Compiler version : AppleClang 9.0.0.9000039
Compiler args: -Wall -Wextra -Wpedantic

Example job producing warnings:
http://ci.ros2.org/job/ci_osx/3283/warnings10Result/

**Comment by scpeters** [comment]
fixed by #64
