### ISSUE TITLE
problem about "logError or logWarn ...undeclared" is solved

### ISSUE THREAD

**Issue by dpluy** [ros/console_bridge#56]
add 
```
#define logWarn CONSOLE_BRIDGE_logWarn
#define logError CONSOLE_BRIDGE_logError
#define logDebug CONSOLE_BRIDGE_logDebug
#define logInform CONSOLE_BRIDGE_logInform
```
to /usr/include/ros/console_bridge/console.h in some cases.

My OS: archlinux 
lend my wisdom.

**Comment by dirk-thomas** [comment]
The short not-namespaced macros where deprecated for a while and have intentionally been removed in #48. The rational is that they collide with function definitions in other code.

Therefore you should update your usage to use the namespaced version of the macros instead.
