### ISSUE TITLE
A lot of undefined references on compiling on arch linux

### ISSUE THREAD

**Issue by ghost** [ros/console_bridge#61]
Tried to compile version 0.4.1 on arch linux and recieved following error.
Please help.
`[ 12%] Linking CXX shared library lib/libconsole_bridge.so
[ 25%] Building CXX object test/CMakeFiles/gtest.dir/gtest/src/gtest-all.cc.obj
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x118): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x149): undefined reference to `std::ostream::put(char)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x151): undefined reference to `std::ostream::flush()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x167): undefined reference to `std::ctype<char>::_M_widen_init() const'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x18e): undefined reference to `std::__throw_bad_cast()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x1e9): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x1fc): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x22d): undefined reference to `std::ostream::put(char)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x235): undefined reference to `std::ostream::flush()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x24e): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x25c): undefined reference to `std::ostream::operator<<(int)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x274): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x293): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x2c1): undefined reference to `std::ostream::put(char)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x2c9): undefined reference to `std::ostream::flush()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x300): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x313): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x344): undefined reference to `std::ostream::put(char)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x34c): undefined reference to `std::ostream::flush()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x368): undefined reference to `std::ctype<char>::_M_widen_init() const'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x399): undefined reference to `std::ctype<char>::_M_widen_init() const'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x3d4): undefined reference to `std::ctype<char>::_M_widen_init() const'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x416): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x431): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x455): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x45f): undefined reference to `std::__throw_bad_cast()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x4b5): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x4e6): undefined reference to `std::ostream::put(char)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x504): undefined reference to `std::ctype<char>::_M_widen_init() const'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x52b): undefined reference to `std::__throw_bad_cast()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x598): undefined reference to `__cxa_guard_acquire'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x5eb): undefined reference to `__cxa_guard_release'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x603): undefined reference to `std::__throw_system_error(int)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x669): undefined reference to `__cxa_guard_acquire'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x6bc): undefined reference to `__cxa_guard_release'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x6d4): undefined reference to `std::__throw_system_error(int)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x748): undefined reference to `__cxa_guard_acquire'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x79b): undefined reference to `__cxa_guard_release'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x7b3): undefined reference to `std::__throw_system_error(int)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x7ed): undefined reference to `__cxa_guard_acquire'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x840): undefined reference to `__cxa_guard_release'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x8ed): undefined reference to `__cxa_guard_acquire'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x940): undefined reference to `__cxa_guard_release'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xa23): undefined reference to `operator delete(void*)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xa4c): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long long&, unsigned long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xae1): undefined reference to `std::__throw_system_error(int)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xaf7): undefined reference to `operator delete(void*)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xb78): undefined reference to `__cxa_guard_acquire'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xbcb): undefined reference to `__cxa_guard_release'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xbe3): undefined reference to `std::__throw_system_error(int)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xc48): undefined reference to `__cxa_guard_acquire'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xc9b): undefined reference to `__cxa_guard_release'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xcb3): undefined reference to `std::__throw_system_error(int)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xd0a): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xd2d): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xd4d): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xd77): undefined reference to `std::ostream::put(char)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xd94): undefined reference to `std::ctype<char>::_M_widen_init() const'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xdd8): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xde2): undefined reference to `std::__throw_bad_cast()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xc8): undefined reference to `std::ios_base::Init::~Init()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xff): undefined reference to `operator delete(void*)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x15f): undefined reference to `operator delete(void*)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x2dd): undefined reference to `std::ostream::flush()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x360): undefined reference to `std::ostream::flush()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0x4f3): undefined reference to `std::ostream::flush()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text+0xd85): undefined reference to `std::ostream::flush()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.xdata+0x4): undefined reference to `__gxx_personality_seh0'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.xdata+0x34): undefined reference to `__gxx_personality_seh0'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.xdata+0x54): undefined reference to `__gxx_personality_seh0'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.xdata+0x68): undefined reference to `__gxx_personality_seh0'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.xdata+0x88): undefined reference to `__gxx_personality_seh0'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.xdata+0xa8): more undefined references to `__gxx_personality_seh0' follow
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text$_ZN14console_bridge16OutputHandlerSTDD0Ev[_ZN14console_bridge16OutputHandlerSTDD0Ev]+0x1): undefined reference to `operator delete(void*)'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.text.startup+0xc): undefined reference to `std::ios_base::Init::Init()'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.rdata$_ZTIN14console_bridge13OutputHandlerE[_ZTIN14console_bridge13OutputHandlerE]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.rdata$_ZTIN14console_bridge16OutputHandlerSTDE[_ZTIN14console_bridge16OutputHandlerSTDE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.rdata$_ZTIN14console_bridge17OutputHandlerFileE[_ZTIN14console_bridge17OutputHandlerFileE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.rdata$.refptr._ZSt4cout[.refptr._ZSt4cout]+0x0): undefined reference to `std::cout'
CMakeFiles/console_bridge.dir/src/console.cpp.obj:console.cpp:(.rdata$.refptr._ZSt4cerr[.refptr._ZSt4cerr]+0x0): undefined reference to `std::cerr'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/console_bridge.dir/build.make:84: lib/libconsole_bridge.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/console_bridge.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** Deleting file 'test/CMakeFiles/gtest.dir/gtest/src/gtest-all.cc.obj'
make[2]: unlink: test/CMakeFiles/gtest.dir/gtest/src/gtest-all.cc.obj: Device or resource busy
make[2]: *** [test/CMakeFiles/gtest.dir/build.make:63: test/CMakeFiles/gtest.dir/gtest/src/gtest-all.cc.obj] Interrupt
make[1]: *** [CMakeFiles/Makefile2:208: test/CMakeFiles/gtest.dir/all] Interrupt
make: *** [Makefile:141: all] Interrupt `

**Comment by scpeters** [comment]
sorry for the delay in responding to this bug report. is this still a problem?

**Comment by scpeters** [comment]
I'm going to close this; please comment if the issue persists and I will re-open.
